export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const EDIT_CONTENT = 'EDIT_CONTENT'
export const SELECT_ITEM = 'SELECT_ITEM'
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_DONE = 'SHOW_DONE'
export const SHOW_DOING = 'SHOW_DOING'
export const DELETE_ALL = 'DELETE_ALL'

export const TEST = 'TEST'